name: ci

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node (placeholder)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps (placeholder)
        run: npm ci || echo "No package.json yet"
      - name: Lint & tests (placeholder)
        run: npm run lint && npm test || echo "No lint/tests yet"

  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
